apiVersion: v1
kind: Service
metadata:
  name: jspweb-service
spec:
  type: NodePort
  selector:
    app: jspweb
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jspweb
  labels:
    app: jspweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jspweb
  template:
    metadata:
      labels:
        app: jspweb
    spec:
      containers:
      - name: jspweb
        image: kubesk071/jspapp:k8s-v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: jspdb

        - name: DB_USER
          value: root

        - name: DB_PASS
          value: root
